site: Wonderkid
url: https://wonderkid.uk
title: Wonderkid
description: Wonderkid is an online magazine, which tells interesting stories about sport with a focus on data analytics.

social_media:
  ko-fi: evanmoss
  twitter: wonderkiduk
  instagram: wonderkiduk
  github: wonderkiduk
  email: hello@wonderkid.uk

google_analytics: G-0GYXY70PKJ

permalink: pretty

paginate:            1000
paginate_path:       "/page:num/"
baseurl:             ""

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:categories/:slug
  projects:
    output: true
    permalink: /projects/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

  - scope:
      path: "assets/images"
    values:
      image: true
